# Generated by Django 5.1 on 2026-04-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=20)),
                ('preference', models.CharField(blank=True, choices=[('sell', 'Sell'), ('rent', 'Rent / Lease'), ('pg', 'PG')], help_text='Optional: if set, this type is only for this preference', max_length=50, null=True)),
            ],
        ),
    ]
