# Generated by Django 5.1 on 2026-04-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_propertytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_status',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_type',
        ),
    ]
