# Generated by Django 5.1 on 2026-04-04 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_property_property_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='dashboard.propertytype'),
        ),
    ]
