# Generated by Django 5.1 on 2026-04-04 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_property_property_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='dashboard.propertytype'),
        ),
    ]
