# Generated by Django 5.1 on 2026-04-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_property_property_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='neighborhood',
            new_name='locality',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='unit_price',
            new_name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='property',
            name='garage_size_sqft',
        ),
        migrations.RemoveField(
            model_name='property',
            name='garages',
        ),
        migrations.RemoveField(
            model_name='property',
            name='land_area_sqft',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='size_sqft',
        ),
        migrations.RemoveField(
            model_name='property',
            name='year_built',
        ),
        migrations.AddField(
            model_name='property',
            name='availability',
            field=models.CharField(choices=[('rtm', 'Ready to Move'), ('construction', 'Under Construction')], default='rtm', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='balconies',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='builtup_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='builtup_area_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='carpet_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='carpet_area_unit',
            field=models.CharField(default='sqft', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='Jaipur', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='house_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='landmark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership',
            field=models.CharField(choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold'), ('cooperative', 'Co-operative'), ('poa', 'Power of Attorney')], default='freehold', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='property_on_floor',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='super_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='super_area_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(default='Rajasthan', max_length=100),
        ),
    ]
