# Generated by Django 5.1 on 2026-04-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_neighborhood_property_locality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='property_videos/'),
        ),
        migrations.AddField(
            model_name='property',
            name='video_type',
            field=models.CharField(default='auto', max_length=10),
        ),
    ]
