# Generated by Django 5.1 on 2026-04-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_property_video_file_property_video_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
